_logo: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1200px-Bootstrap_logo.svg.png
_banner: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1200px-Bootstrap_logo.svg.png

nav_menu:
  主页: /
  归档: archives/

color:
  title: primary # 大标题颜色
  subtitle: white # 副标题颜色
  tag: warning #标签颜色
  badge: primary #文章数颜色